src/backend/activity/urls.py
from django.urls import path

from . import views

app_name = 'activity'

urlpatterns = [
    path('', views.index, name='dashboard'),
    path('task/<int:task_id>/', views.task_view, name='task'),
    path('answer/<int:answer_pk>', views.get_answer, name='answer'),

]

src/backend/rooms/urls.py
from django.urls import path

from . import views

app_name = 'rooms'

urlpatterns = [
    path('login/<str:room_name>/', views.login, name='login'),
    path('room/<str:room_name>/', views.room, name='room'),
]

src/backend/rooms/models.py
from django.db import models
from django.shortcuts import reverse
from shortuuidfield import ShortUUIDField
from django.utils import timezone


# Create your models here.


class StudentGroup(models.Model):
    GROUP_STARTED = 'ST'
    GROUP_FINISHED = 'FI'
    STATUSES = (
        (GROUP_STARTED, 'Начали работать'),
        (GROUP_FINISHED, 'Закончили работать')
    )
    uid = ShortUUIDField(primary_key=True, max_length=10, verbose_name='Номер группы', editable=False)
    job_status = models.CharField(verbose_name='Статус выполнения', max_length=2,
                                  choices=STATUSES, blank=True, default='')
    points = models.IntegerField(verbose_name='Баллы', default=0)
    started = models.DateTimeField(verbose_name='Начали выполнять', editable=False, null=True, blank=True)
    finished = models.DateTimeField(verbose_name='Закончили выполнять', editable=False, null=True, blank=True)
    activity = models.ForeignKey('activity.Activity', verbose_name='Активность', related_name='students_groups',
                                 on_delete=models.CASCADE)
    additional_exercises = models.ManyToManyField('activity.Exercise', verbose_name='Доп. задания', blank=True)

    class Meta:
        ordering = ['activity']

    def __str__(self):
        return f'{self.activity.name}, {self.uid}'

    def get_absolute_url(self):
        return reverse('rooms:login', kwargs={'room_name': self.uid})

    def set_group_start(self):
        self.job_status = self.GROUP_STARTED
        self.started = timezone.now()
        self.save(update_fields=['job_status', 'started'])
        return self

    def set_group_finish(self):
        self.job_status = self.GROUP_FINISHED
        self.finished = timezone.now()
        self.save(update_fields=['job_status', 'finished'])
        return self


class Student(models.Model):
    uid = ShortUUIDField(primary_key=True, max_length=10, verbose_name='uid', editable=False)
    name = models.CharField(verbose_name='Имя студента', max_length=100)
    group = models.ForeignKey(StudentGroup, verbose_name='Группа', related_name='students', on_delete=models.CASCADE)
    ready = models.BooleanField(verbose_name='Готов', default=False, editable=False)
    online = models.BooleanField(verbose_name='Статус онлайн', default=True, editable=False)

    def __str__(self):
        return self.name

    def set_online(self, status: bool):
        self.online = status
        return self.save(update_fields=['online', ])

    def set_ready(self, status: bool):
        self.ready = status
        return self.save(update_fields=['ready', ])

src/backend/rooms/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from .models import StudentGroup, Student
from channels.layers import get_channel_layer
from asgiref.sync import async_to_sync


def login(request, room_name):
    if request.user.is_authenticated:
        return redirect('rooms:room', room_name)

    if request.session.get('uid'):
        user = Student.objects.get(pk=request.session.get('uid'))

        return redirect('rooms:room', user.group_id)

    if request.method == 'GET':
        return render(request, 'index.html', {'group_name': room_name})

    elif request.method == 'POST':
        name = request.POST.get('username')
        student, _ = Student.objects.get_or_create(name=name, group_id=room_name)
        request.session['uid'] = student.pk
        student.set_online(True)
        student.save()
        return redirect('rooms:room', room_name)


def room(request, room_name):
    group = StudentGroup.objects.get(pk=room_name)
    tasks = group.activity.tasks.all()
    students = group.students.filter(online=True)
    answers = group.answer_set.all()
    if request.user.is_authenticated:
        user = request.user
    else:
        uid = request.session['uid']
        user = Student.objects.get(pk=uid)

    channel_layer = get_channel_layer()
    async_to_sync(channel_layer.group_send)(
        f'room_{room_name}', {
            'type': 'users_list',
        }
    )
    return render(request, 'room.html', {
        'group': group,
        'tasks': tasks,
        'answers': answers,
        'students': students,
        'user': user
    })

src/backend/rooms/templates/inc-room-user-list.html
{% for stud in students %}
    <li id="{{ stud.pk }}" data-uid="{{ stud.pk }}" class="{% if stud.ready %}user-ready{% endif %}">
        {{ stud.name }}
    </li>
{% endfor %}

src/backend/rooms/templates/inc-tasks-list.html
<ul id="tasksList">
    {% for task in tasks %}
        <li data-task-id="{{ task.pk }}"
            class="task-item {% if not group.job_status == 'ST' or group.job_status == 'FI' %}inactive-task{% endif %}">
            {% if not group.job_status == 'ST' or group.job_status == 'FI' %}
                {{ task.category }}
            {% else %}
                <a href="#" id="task-link-{{ task.pk }}" data-url="{% url "activity:task" task_id=task.pk %}"
                   onclick=get_task({{ task.pk }})>

                    {{ task.category }}
                    {% for answer in answers %}
                        {% if answer.task.pk == task.pk %}

                            <span class="{{ answer.status }}"></span>
                        {% endif %}
                    {% endfor %}
                </a>
            {% endif %}
        </li>
    {% endfor %}
</ul>

src/backend/rooms/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Добро пожаловать</title>
</head>
<body>
<h3>Ваша группа: {{ group_name }}</h3>

Введите ваше имя:<br>

<form action="{% url 'rooms:login' room_name=group_name %}" method="POST">
    {% csrf_token %}
    <input name="username" type="text" size="100" required><br>
    <button id="user-name-submit" type="submit">Enter</button>
</form>

</body>
</html>

src/backend/rooms/templates/room.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Rooms{% endblock %}


{% block content %}
    <nav class="navbar navbar-expand-lg navbar-light bg-light mb-4">
        <div class="container">
            <span class="navbar-brand"><img src="{% static "img/logo.png" %}" height="80" alt="logo"></span>
            {#            <div class="container">#}
            <span class="navbar-text navbar-points">1500 <br> балла</span>
            <span class="navbar-text nav-activity">{{ group.activity.name|upper }}</span>
            <span class="navbar-text navbar-points">60 мин.</span>
            {#            </div>#}
        </div>
    </nav>
    <div class="container-fluid" id="group-room" data-room-id="{{ group.pk }}">
        <div class="row">
            <div class="col-4">
                <div class="row">
                    {% include "inc-tasks-list.html" %}
                </div>
            </div>
            <div class="col-8">
                <div id="answer-block" class="mb-4">
                    <h4>Пользователи в комнате:</h4>
                    <div class="row">

                        <ul id="userList">
                            {% include "inc-room-user-list.html" %}
                        </ul>

                    </div>
                    <div class="row">
                        <p>
                            {% if not request.user.is_athenticated and not user.ready %}
                                <button id="student-ready" class="input-button" data-uid="{{ user.pk }}">
                                        <span>Готов к
                                        выполнению!</span>
                                </button>
                            {% endif %}
                        </p>
                    </div>
                </div>

            </div>
        </div>
    </div>

{% endblock %}


{% block scripts %}
    <script>
        let roomName = $('#group-room').data('room-id');

        let roomSocket = new WebSocket(
            'ws://' + window.location.host + '/rooms/room/' + roomName + '/');

        roomSocket.onclose = function (e) {
            console.error('room socket closed unexpectedly')
        };

        roomSocket.onmessage = function (e) {
            let data = JSON.parse(e.data);
            let users = data['users_list'];
            let tasks = data['tasks'];
            if (users !== undefined) {
                $('#userList').html(users)
            }

            if (tasks !== undefined) {
                $('#tasksList').html(tasks)
            }

        };

        $('#student-ready').click(function (e) {
            let userReady = {
                'user_ready': $(this).data('uid')
            };

            roomSocket.send(JSON.stringify(userReady));

            $('#student-ready').remove();
        });
    </script>
    <script>
        function get_task(task_id) {
            let url = $('a#task-link-' + task_id).data('url');
            $.get(url, function (data) {
                $('#answer-block').html(data)
            })
        }
    </script>
{% endblock %}